# Generated by Django 4.1.3 on 2022-11-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=254)),
                ('Description', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Inventory_Quantity', models.IntegerField()),
            ],
        ),
    ]
